# Generated by Django 5.1.4 on 2025-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_staff_rename_shop_id_shop_shopid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='contact',
            new_name='address',
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default=1234, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
