# Generated by Django 5.1.5 on 2025-01-20 07:58

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_contact_staff_address_staff_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='currentSockSupplied',
        ),
        migrations.RemoveField(
            model_name='item',
            name='currentStockBalance',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dateCurrentStockBalance',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dateCurrentStockSupplied',
        ),
        migrations.RemoveField(
            model_name='item',
            name='datePreviousStockBalance',
        ),
        migrations.RemoveField(
            model_name='item',
            name='datePreviousStockSupplied',
        ),
        migrations.RemoveField(
            model_name='item',
            name='previousStockBalance',
        ),
        migrations.RemoveField(
            model_name='item',
            name='previousStockSupplied',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='item',
            name='totalStockSupplied',
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopID',
            field=models.CharField(default=dashboard.models.generate_shop_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffID',
            field=models.CharField(default=dashboard.models.generate_staff_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('salesID', models.CharField(default=dashboard.models.generate_sales_id, max_length=10, primary_key=True, serialize=False)),
                ('saleType', models.CharField(choices=[('stock_supplied', 'Stock Supplied'), ('stock_balance', 'Stock Balance')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.staff')),
            ],
        ),
    ]
